run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    # Deprecated linters
    - varcheck
    - exhaustivestruct
    - ifshort
    - structcheck
    - golint
    - maligned
    - interfacer
    - nosnakecase
    - deadcode
    - scopelint
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign
    # Ignoring
    - lll
    - varnamelen
    - paralleltest
    - testpackage
    - goerr113
    - exhaustruct
    - nestif
    - funlen
    - goconst
    - cyclop
    - gocyclo
    - gocognit
    - maintidx
    - contextcheck
